hrm/urls.py
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    
    path('api/company/', views.CompanyList.as_view()),
    path('api/profile/', views.ProfileList.as_view()),
    path('api/employee/', views.EmployeeList.as_view()),
    path('supervisor/<int:pk>/', views.TeamManagerProfileView.as_view()),
    path('members/', views.MembersView.as_view()),
    path('team/<int:pk>/', views.TeamView.as_view()),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hrms/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrm.urls')),
    path('api/v1/', include('apps.authentication.urls')),
    path('logout/', auth_views.LogoutView.as_view(), {"next_page":'/'}),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

hrm/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model as user_model
User = user_model()
from django.db import models
from cloudinary.models import CloudinaryField
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from tinymce.models import HTMLField
import datetime as dt
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from datetime import datetime
from django.utils.translation import ugettext as _
from django.utils import timezone
from datetime import datetime

class Hradmin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
 
# class EmployeeProfile(models.Model):
# 	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
# 	name = models.CharField(max_length=200, null=True)
# 	phone = models.CharField(max_length=200, null=True)
# 	email = models.CharField(max_length=200, null=True)
# 	date_created = models.DateTimeField(auto_now_add=True, null=True)
	   

class Team(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(max_length=1024)
    logo = CloudinaryField('image', null=True)
    members = models.ManyToManyField(User, through='members')
    
    def __str__(self):
        return self.team_name



# class TeamManager(models.Manager):
#     use_for_related_fields = True

#     def add_member(self, user, team):
#         pass
        
class TeamManagerProfile(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    phone_number = models.IntegerField(blank=True, null= True)
    bio = models.TextField(blank=True)
    profile_photo = CloudinaryField('image', null=True)
    team_name = models.ForeignKey(Team , max_length=50, blank=True, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name 


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:  
        if instance.is_teamlead:  
            TeamLeadProfile.objects.create(user=instance) 

        else:
            pass
    


class MembersProfile(models.Model):
    team_name = models.ForeignKey(Team ,max_length=50, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #employee = models.ForeignKey(User, null=True, on_delete=models.CASCADE)


    # objects = TeamManager()

# Create your models here.
SICK = 'sick'
CASUAL = 'casual'
EMERGENCY = 'emergency'
STUDY = 'study'

LEAVE_TYPE = (
(SICK,'Sick Leave'),
(CASUAL,'Casual Leave'),
(EMERGENCY,'Emergency Leave'),
(STUDY,'Study Leave'),
)

DAYS = 30

class Leave(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
	startdate = models.DateField(verbose_name=_('Start Date'),help_text='leave start date is on ..',null=True,blank=False)
	enddate = models.DateField(verbose_name=_('End Date'),help_text='coming back on ...',null=True,blank=False)
	leavetype = models.CharField(choices=LEAVE_TYPE,max_length=25,default=SICK,null=True,blank=False)
	reason = models.CharField(verbose_name=_('Reason for Leave'),max_length=255,help_text='add additional information for leave',null=True,blank=True)
	is_approved = models.BooleanField(default=False) #hide

	def __str__(self):
		return ('{0} - {1}'.format(self.leavetype,self.user))

	@property
	def pretty_leave(self):
		
		leave = self.leavetype
		user = self.user
		employee = user.employee_set.first().get_full_name
		return ('{0} - {1}'.format(employee,leave))

	@property
	def leave_days(self):
		days_count = ''
		startdate = self.startdate
		enddate = self.enddate
		if startdate > enddate:
			return
		dates = (enddate - startdate)
		return dates.days

class Company(models.Model):
    logo = CloudinaryField('image', null=True)
    description = HTMLField()
    name =models.CharField(max_length=100)
    email = models.EmailField()
    location =models.CharField(max_length=100)
    contact = PhoneNumberField()

    def __str__(self):
        return self.name
      
class Profile(models.Model):
    avatar = CloudinaryField('image', null=True)
    username = models.ForeignKey(User,on_delete=models.CASCADE)
    name =models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.IntegerField()

    def __str__(self):
        return self.name

class Employee(models.Model):
    avatar = CloudinaryField('image', null=True)
    name =models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.IntegerField()
    address =models.CharField(max_length=100)

    def __str__(self):
        return self.name

hrm/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from .models import *
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
# from .serializer import
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
import datetime
from django.contrib import messages
from .serializers import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from rest_framework import status



class TeamManagerProfileView(APIView):
    permission_classes = (IsAuthenticated,)
    def check_role(self, request):
        if request.user.is_supervisor:
            pass
        else:
            raise Http404()       
    
    def get_teammanager(self, pk):
        try:
            return TeamManagerProfile.objects.get(pk=pk)
        except TeamManagerProfile.DoesNotExist:
            raise Http404()
    

    def get(self, request, pk, format=None):
        self.check_role(request)
        this_teammanager = self.get_supervisor(pk)
        serializers = TeamManagerSerializer(this_teammanager)
        return Response(serializers.data)

    def put(self, request, pk, format=None):
        self.check_role(request)
        this_supervisor = self.get_supervisor(pk)
        serializers = TeamManagerSerializer(this_teamManager, request.data, partial=True)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        else:
            return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        self.check_role(request)
        this_teammanager = self.get_teammanager(pk)
        this_teammanager.user.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)



class MembersView(APIView):
    permission_classes = (IsAuthenticated,)
    def check_role(self, request):
        if request.user.is_teammanager:
            pass
        else:
            raise Http404()    

    def get(self, request, format=None):
        self.check_role(request)
        all_members = Member.objects.all()
        serializers = MemberSerializer(all_members, many=True)
        return Response(serializers.data) 

    def post(self, request, format=None):
        self.check_role(request)
        serializers = MemberSerializer(data=request.data, partial=True)
        if serializers.is_valid():
            this_member_id = int(serializers.validated_data['member_id_num'])
            this_member = MemberProfile.objects.get(pk=this_member_id)
            serializers.save(member=this_member)
            return Response(serializers.data, status=status.HTTP_201_CREATED)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)


class TeamView(APIView):
    permission_classes = (IsAuthenticated,)
    def check_role(self, request):
        if request.user.is_teammanager or request.user.is_teammanager:
            pass
        else:
            raise Http404()       
    
    def get_team(self, pk):
        try:
            return Team.objects.get(pk=pk)
        except Team.DoesNotExist:
            raise Http404()
    

    def get(self, request, pk, format=None):
        self.check_role(request)
        this_team = self.get_team(pk)
        serializers = TeamSerializer(this_department)
        return Response(serializers.data)


    def put(self, request, pk, format=None):
        self.check_role(request)
        this_team = self.get_team(pk)
        serializers = TeamSerializer(this_team, request.data, partial=True)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        else:
            return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)


    def delete(self, request, pk, format=None):
        self.check_role(request)
        this_team = self.get_team(pk)
        this_team.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

# def employee_profile_view(request):
	
#   if request.method == 'POST':
		
#     user_form = UserForm(request.POST, prefix='UF')
# 		profile_form = EmployeeProfileForm(request.POST, prefix='PF')
		
#     if user_form.is_valid() and profile_form.is_valid():
# 			user = user_form.save(commit=False)
# 			user.save()

# 			user.employee_profile.name = profile_form.cleaned_data.get('name')
#             user.employee_profile.avatar = profile_form.cleaned_data.get('file')
# 			user.employee_profile.phone = profile_form.cleaned_data.get('phone')
#             user.employee_profile.email = profile_form.cleaned_data.get('email')

# 			user.employee_profile.save()
			
# 	else:
# 		user_form = UserForm(prefix='UF')
# 		profile_form = EmployeeProfileForm(prefix='PF')
		
# 	return render(request, '',{
			
# 		})

# Create your views here.
class CompanyList(APIView):
    def get(self, request, format=None):
        all_companies = Company.objects.all()
        serializers = CompanySerializer(all_companies, many=True)
        return Response(serializers.data)

class ProfileList(APIView):
    def get(self, request, format=None):
        hr_profiles = Profile.objects.all()
        serializers = ProfileSerializer(hr_profiles, many=True)
        return Response(serializers.data)

class EmployeeList(APIView):
    def get(self, request, format=None):
        all_employees = Employee.objects.all()
        serializers = EmployeeSerializer(all_employees, many=True)
        return Response(serializers.data)

class Leave_creation(APIView):
    def leave_creation(request):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        if request.method == 'POST':
            form = LeaveCreationForm(data = request.POST)
            if form.is_valid():
                instance = form.save(commit = False)
                user = request.user
                instance.user = user
                instance.save()

                messages.success(request,'Leave Request Sent,wait for Human Resource Managers response',extra_tags = 'alert alert-success alert-dismissible show')
                return redirect('createleave')

            messages.error(request,'failed to Request a Leave,please check entry dates',extra_tags = 'alert alert-warning alert-dismissible show')
            return redirect('createleave')


        dataset = dict()
        form = LeaveCreationForm()
        dataset['form'] = form
        dataset['title'] = 'Apply for Leave'
        return render(request,'leaves/create_leave.html',dataset)

# def leave_creation(request):
# 	current_user = request.user
	
# 	if request.method == 'POST':
# 		form = LeaveCreationForm(request.POST, request.FILES)
# 		if form.is_valid():
# 			instance = form.save(commit = False)
# 			instance.user = current_user
# 			instance.save()
# 		return redirect('createleave')
# 	else:
#         form = LeaveCreationForm()
# 		return render(request,'leaves/create_leave.html', {"form":form})



def leaves_list(request):
	if not (request.user.is_staff and request.user.is_superuser):
		return redirect('/')
	leaves = Leave.objects.all()
	return render(request,'leaves/leaves_recent.html',{'leave_list':leaves,'title':'leaves list'})

def leaves_view(request,id):
	current_user = request.user
    #connect to the registered employees
	leave = get_object_or_404(Leave, id = id)
	employee = Employee.objects.filter(user = leave.user)[0]
	print(employee)
	return render(request,'leaves/leave_detail_view.html',{'leave':leave,'employee':employee,'title':'{0}-{1} leave'.format(leave.user.username,leave.status)})


@login_required(login_url='/accounts/login/')
def companies(request):
    current_user=request.user
    profile=Profile.objects.get(username=current_user)
    companies = Company.objects.all()

    return render(request,'companies.html',{"companies":companies})

@login_required(login_url='/accounts/login/')
def employee(request):
    current_user=request.user
    profile=Profile.objects.get(username=current_user)
    employees=Employee.objects.all()

    return render(request,'employee.html',{"employees":employees})


@login_required(login_url='/accounts/login/')
def user_profile(request):
    current_user=request.user
    profile =Profile.objects.get(username=current_user)
    if request.method=="POST":
        instance = Profile.objects.get(username=current_user)
        form =ProfileForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.username = current_user
            profile.save()

        return redirect('profile')

    elif Profile.objects.get(username=current_user):
        profile = Profile.objects.get(username=current_user)
        form = ProfileForm(instance=profile)
    else:
        form = ProfileForm()

    return render(request,'profile.html',{"profile":profile, "form":form})

hrm/templates/leaves/create_leave.html
{% extends 'leaves/layout.html' %} {% load bootstrap4 %} {% load static %} {% load cloudinary %} {% block content %}
<section class="content">
    <section class="container-fluid">

        <section class="form-wrapper">
            <section class="row">
                <section class="col col-lg-12 col-md-12  col-sm-12">

                    {% if messages %} {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                        {{ message }}
                        <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                    </div>
                    {% endfor %} {% endif %}

                </section>
            </section>

            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12 text-center space-margin">
                    <h3 class="title-h3">{{title}}</h3>
                </section>
            </section>

            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12">
                    <form action="{%url 'createleave'%}" method="POST" enctype="multipart/formdata">
                        {% csrf_token %} {% bootstrap_form form %}
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Send Request</button>
                    </form>
                </section>

            </section>

        </section>

    </section>
    <!-- /container -->
</section>
{% endblock %}

hrm/templates/leaves/layout.html
{% load bootstrap4 %} {% load static %} {% load cloudinary %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" /> {% if title %}
    <title> HRM {{title}}</title>
    {% else %}
    <title> HRM </title>
    {% endif %} {% block styles %} {% bootstrap_css %}

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'leaves.css' %}" rel="stylesheet" />


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> {% endblock styles %}

</head>

<body>

    {% include 'navbar.html' %} {% block content %} {%endblock%} {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {{block.super}}


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/clipboard.js/1.5.3/clipboard.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>


    <!--   Core JS Files   -->
    <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

    <!--  Charts Plugin -->
    <script src="{% static 'js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>


    <script type="text/javascript">
        function previewImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('.prev-holder .prev-avatar').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }


        $(document).ready(function() {

            $('.refresh-page').click(function() {
                /*Script refreshes the page*/
                console.log('refresh page clicked !!!');
                location.reload(true);

            });


            $("#id_birthday,#id_dateissued,#id_startdate,#id_enddate").datepicker({
                dateFormat: 'yy-mm-dd'
            });


        });
    </script>

    {% endblock %}
</body>

</html>

hrm/templates/leaves/leave_detail_view.html
{% load bootstrap4 %} {% load static %} {% load cloudinary %} {% block content %}
<div class="content">
    <div class="container-fluid">

        <div class="form-wrapper">
            <div class="row">
                <div class="col col-lg-8 col-md-12  col-sm-12">

                    {% if messages %} {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                        {{ message }}
                        <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                    </div>
                    {% endfor %} {% endif %}

                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 text-center space-margin">
                    <h3 class="title-h3">{{ employee.get_full_name }}</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4 text-center">
                    <img src="{{ employee.image.url}}" class="img-fluid rounded-circle-image">
                </div>
                <div class="col-lg-8 col-md-12 col-sm-12">
                    <div class="list-group" id="list-tab" role="tablist">
                        <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Employee</span> <div>{{ employee.get_full_name }}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Start Date</span> <div> Start Date {{ leave.startdate }}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="" role="tab" aria-controls=""><span>End Date</span><div>{{ leave.enddate}}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Duration</span> <div>{{ leave.leave_days}}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Type</span> <div>{{ leave.leavetype}}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Reason</span> <div>{{ leave.reason}}</div>
                                            </a>

                    </div>

                </div>
            </div>

        </div>

    </div>
    <!-- /container -->
</div>
{% endblock %}

hrm/templates/leaves/leaves_recent.html
{% load bootstrap4 %} {% load static %} {% load cloudinary %} {% block content %}
<section class="content">
    <section class="container-fluid">
        <section class="row">
            <section class="col col-sm-8 offset-sm-2">

                {% if messages %} {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                    {{ message }}
                    <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                </div>
                {% endfor %} {% endif %}

            </section>
        </section>

        <!-- TABLE -->
        <div class="table-responsive table-shadow">
            <div class="text-center table-description">
                <h4 class="title-h3" style="color: #60a0b3 !important;
    						text-shadow: 1px 0px rgba(0,0,0,0.11)">ALL LEAVES</h4>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <!-- <th scope="col">#</th> -->
                        <th scope="col">User</th>
                        <th scope="col">Type</th>
                        <th scope="col">Day(s)</th>
                        <th scope="col">Status</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for leave in leave_list %}
                    <tr>

                        <td>{{ leave.user }}</td>
                        <td>{{ leave.leavetype}}</td>
                        <td>{{ leave.leave_days }}</td>
                        <td>{{ leave.status }}</td>

                        <td>
                            <a href="{% url 'userleaveview' leave.id %}">
                                <span>view</span>
                            </a>

                        </td>
                    </tr>

                    {% endfor %}

                </tbody>

            </table>

        </div>
        <!-- /TABLE -->

    </section>
    <!-- /container -->


</section>
{% endblock %}